output_dir: './workdir/run_active_learning'
hydra:
  run:
    dir: ${output_dir}/${now:%Y-%m-%d}/${now:%H-%M-%S}_${seed}_${to_string:${acquisition_model.checkpoint}}
  sweep:
    dir: ${output_dir}/${now:%Y-%m-%d}/${now:%H-%M-%S}_${seed}_${to_string:${acquisition_model.checkpoint}}
    subdir: ${hydra.job.num}

seed: 42
cuda_device: 0
cache_dir: ./${output_dir}/cache_${seed}_${to_string:${acquisition_model.checkpoint}}
cache_model_and_dataset: False
framework: 'pytorch'
task: 'ner'
offline_mode: False

data:
    dataset_name: 'conll2003'
    path: 'datasets' # 'datasets' if we want to use Hugging Face datasets
    tag_index: 2
    text_name: 'tokens'
    label_name: 'ner_tags'
    labels_to_remove:
    seed: ${seed}

acquisition_model:
    type: ${task}
    embeddings_path: 'word2vec' # add cnn-specific params
    embeddings_cache_dir: './workdir/run_active_learning/embeddings'
    freeze_embedding: False
    vocab_size: None
    embed_dim: 300
    checkpoint: 'bilstm'
    tokenizer_max_length:
    classifier_dropout: 0.2
    exists_in_repo: False # whether the model exists in HF models repo
    path_to_pretrained: # required if the model does not exist in HF models repo
    training:
        dev_size: 0.1
        shuffle_dev: False
        freeze_embedder: False
        batch_size_args:
            batch_size: 16
            eval_batch_size: 100
            min_num_gradient_steps: 1000
            adjust_batch_size: True
            adjust_num_epochs: True
            min_batch_size: 4
        trainer_args:
            num_epochs: 15
            patience: ${get_patience_value:${acquisition_model.training.dev_size}} # 1000 if no dev size else 3
            grad_clipping: 1.
            serialization_dir: ./output/${to_string:${acquisition_model.checkpoint}}_${seed}_${now:%Y-%m-%d}_${now:%H-%M-%S}/acquisition
            validation_metric: 'overall_f1'
            evaluation_strategy: 'no' # for transformers wrapper, 'epoch' or 'steps' or 'no'
            eval_metrics:
            fp16:
                training: True
                evaluation: False
            accumulation:
                gradient_accumulation_steps: 1
                eval_accumulation_steps:
        optimizer_args:
            weight_decay: 0.0
            lr: 1e-3
        scheduler_args:
            warmup_steps_factor: 0.0
            use_adafactor: False

successor_model:

al:
    strategy: 'mnlp'
    mc_iterations: 10
    num_queries: 15
    init_p_or_n: 0.02
    step_p_or_n: 0.02
    split_by_tokens: True
    gamma_or_k_confident_to_save: 0.25
    T: 0.1
    sampling_type:
    evaluate_query: True
    iters_to_recalc_scores: [0, 1, 4, 8]
    strategy_kwargs:
